---
# tasks file for app-pip-install-requirements

- name: pip install requirements
  pip: >
    requirements={{ REQUIREMENTS_NAME }}
    virtualenv={{ VIRTUAL_ENV }}
    extra_args={{ PIP_EXTRA_ARGS }}
    state=latest
  when: INSTALL_TOGGLE_VAR 

- name: wheel install requirements
  command: "{{ VIRTUAL_ENV_ATMOSPHERE }}/bin/wheel install-scripts {{ item }}"
  with_items: "{{ WHEEL_INSTALL_SCRIPT_PACKAGES }}"
  when: RUN_WHEEL_SCRIPTS
  register: output

- debug: var=output.results
  when: "{{ CLANK_VERBOSE | default(False) }}"
