---
# tasks file for config-nginx-uwsgi

- debug: var=UWSGI_INI_SRC_NAME
  when: "{{ DEBUG_OR_TEST_ROLE | default(False) }}"

- name: create apps-enabled directory
  file: path={{ UWSGI_APPS_ENABLED_PATH }} state=directory

- name: link {{ UWSGI_APP_NAME | default('') }} uwsgi conf file
  file: src={{ UWSGI_APP_SRC }} dest={{ UWSGI_APP_DEST }} state=link
  tags:
    - deploy

- name: make nginx configuration files
  shell: make
  args:
    chdir: "{{ APP_BASE_DIR }}/extras/nginx"
  register: output
  tags:
    - deploy

- block:

  - stat: path={{ NGINX_COMBINED_CERT_PATH }}
    register: combined_cert_path

  - name: redefine variables definition for SSL_CERTIFICATE
    set_fact:
      nginx_ssl_cert: "{{ NGINX_CERT_DIR }}/{{ NGINX_CERT_FILE }}"
    when: not SSL_CERTIFICATE

  - name: set variables definition from SSL_CERTIFICATE
    set_fact:
      nginx_ssl_cert: "{{ SSL_CERTIFICATE }}"
    when: "{{ SSL_CERTIFICATE is not none }}"

  - name: redefine variable definition for BUNDLE_CERT
    set_fact:
      nginx_bundle_cert: "{{ NGINX_CERT_DIR }}/{{ NGINX_BUNDLE_FILE }}"
    when: not BUNDLE_CERT

  - name: set variables definition from BUNDLE_CERT
    set_fact:
      nginx_bundle_cert: "{{ BUNDLE_CERT }}"
    when: "{{ BUNDLE_CERT is not none }}"

  - name: generate a combined certificate - combined_cert_source
    command: >
      cat {{ nginx_ssl_cert }} {{ nginx_bundle_cert }}
    register: combined_cert_source
    when: combined_cert_path.stat.exists == False

  - name: local_action copy combined_cert_source to the NGINX_COMBINED_CERT_PATH listed
    local_action: copy content={{ combined_cert_source.stdout }} dest={{ NGINX_COMBINED_CERT_PATH }}
    when: "{{ combined_cert_source.stdout_lines is defined }}"

- debug: var=output.stdout_lines
  when: "{{ CLANK_VERBOSE | default(False) }}"

