VIRTUAL_ENV_DIR_ATMOSPHERE: /opt/env
VIRTUAL_ENV_ATMOSPHERE: "{{ VIRTUAL_ENV_DIR_ATMOSPHERE }}/atmo"

ATMOSPHERE_DIR: /opt/dev
ATMOSPHERE_LOCATION: "{{ ATMOSPHERE_DIR }}/atmosphere"

POSTGRES_SQL_INSTALL_DIRECTORY: /var/lib/postgresql
ATMOSPHERE_DATABASE_FILE_TO_BE_LOADED: # an absolute path to sql script that you want loaded /root/some_sql.sql

ID_RSA:             #Absolute Path Recommende
ID_RSA_PUB:         #Absolute Path Recommended

UWISGI_APPS_ENABLED_PATH: /etc/uwsgi/apps-enabled

WEBSERVER_USER: www-data

JENKINS: false
