VIRTUAL_ENV_DIR_ATMOSPHERE: /opt/env
VIRTUAL_ENV_ATMOSPHERE: "{{ VIRTUAL_ENV_DIR_ATMOSPHERE }}/atmo"

ATMOSPHERE_DIR: /opt/dev
ATMOSPHERE_LOCATION: "{{ ATMOSPHERE_DIR }}/atmosphere"

UWISGI_APPS_ENABLED_PATH: /etc/uwsgi/apps-enabled

WEBSERVER_USER: www-data

JENKINS: false
