---
# tasks file for app-backup-postgres

- name: Create "backups" directory
  file:
    path: "{{ BACKUP_PATH }}/{{ ansible_date_time.date }}"
    state: directory
    owner: postgres
    group: postgres
    mode: 0770

- name: Backup all tables (including system tables)
  become: yes
  become_user: postgres
  args:
    chdir: "{{ BACKUP_PATH }}/{{ ansible_date_time.date }}"
  command: >
    pg_dumpall -f "{{ ansible_hostname }}-all-backup-{{ ansible_date_time.date }}-{{ ansible_date_time.epoch }}.sql"

- name: Backup specific tables ({{ database_names }})
  become: yes
  become_user: postgres
  args:
    chdir: "{{ BACKUP_PATH }}/{{ ansible_date_time.date }}"
  with_items: "{{ database_names }}"
  command: >
    pg_dump {{ item }} -f "{{ ansible_hostname }}-{{ item }}-backup-{{ ansible_date_time.date }}-{{ ansible_date_time.epoch }}.sql"
