---
- name: Create an Atmosphere and Troposphere stack
  hosts: full_deploy

  roles:
    - { role: print-all-variables,
        tags: ['print-vars'] }


- import_playbook: ./prepare_host.yml
- import_playbook: ./deploy_atmosphere.yml
- import_playbook: ./deploy_troposphere.yml

- name: Configure nginx
  hosts: full_deploy
  roles:
    - { role: configure-nginx,
        SERVER_URL: "https://{{ server_name }}",
        SITE_SERVER_NAME: "{{ server_name }}",
        ALTERNATE_SERVER_NAMES: "{{ ADDITIONAL_ALLOWED_HOSTNAMES|default([]) }}",
        LOCATIONS: "{{ nginx_locations }}",
        SSL_KEY: "{{ TLS_PRIVKEY_PATH }}",
        SSL_CERT: "{{ TLS_FULLCHAIN_PATH }}",
        SSL_CACHAIN_CERT: "{{ TLS_CACHAIN_PATH }}",
        TROPO_ASSETS_PATH: "{{ TROPO.COMMON.ASSETS_PATH }}",
        FLOWER_SERVER_URL: "http://127.0.0.1:{{ FLOWER_PORT }}",
        tags: ['nginx'] }

- import_playbook: ./post_deployment.yml
